[2024-01-08T08:23:18.954+0000] {processor.py:161} INFO - Started process (PID=6068) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:23:18.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:23:18.959+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:23:18.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:23:19.117+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:23:19.115+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:23:19.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:23:19.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.188 seconds
[2024-01-08T08:23:49.899+0000] {processor.py:161} INFO - Started process (PID=6132) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:23:49.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:23:49.906+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:23:49.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:23:50.144+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:23:50.140+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:23:50.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:23:50.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.284 seconds
[2024-01-08T08:24:20.746+0000] {processor.py:161} INFO - Started process (PID=6196) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:24:20.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:24:20.753+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:24:20.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:24:20.947+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:24:20.944+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:24:20.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:24:20.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.234 seconds
[2024-01-08T08:24:51.407+0000] {processor.py:161} INFO - Started process (PID=6260) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:24:51.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:24:51.413+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:24:51.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:24:51.642+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:24:51.596+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:24:51.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:24:51.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.269 seconds
[2024-01-08T08:25:22.524+0000] {processor.py:161} INFO - Started process (PID=6324) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:25:22.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:25:22.529+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:25:22.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:25:22.659+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:25:22.657+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:25:22.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:25:22.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.155 seconds
[2024-01-08T08:25:53.040+0000] {processor.py:161} INFO - Started process (PID=6388) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:25:53.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:25:53.045+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:25:53.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:25:53.199+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:25:53.196+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:25:53.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:25:53.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.181 seconds
[2024-01-08T08:26:23.470+0000] {processor.py:161} INFO - Started process (PID=6452) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:26:23.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:26:23.477+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:26:23.477+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:26:23.622+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:26:23.619+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:26:23.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:26:23.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.174 seconds
[2024-01-08T08:26:54.161+0000] {processor.py:161} INFO - Started process (PID=6516) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:26:54.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:26:54.165+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:26:54.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:26:54.454+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:26:54.452+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:26:54.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:26:54.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.312 seconds
[2024-01-08T08:27:24.679+0000] {processor.py:161} INFO - Started process (PID=6578) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:27:24.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:27:24.686+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:27:24.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:27:24.908+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:27:24.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:27:24.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:27:24.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.246 seconds
[2024-01-08T08:27:55.470+0000] {processor.py:161} INFO - Started process (PID=6642) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:27:55.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:27:55.476+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:27:55.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:27:55.685+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:27:55.684+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:27:55.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:27:55.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.231 seconds
[2024-01-08T08:28:26.235+0000] {processor.py:161} INFO - Started process (PID=6705) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:28:26.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:28:26.242+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:28:26.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:28:26.955+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:28:26.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:28:26.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:28:27.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.804 seconds
[2024-01-08T08:35:55.706+0000] {processor.py:161} INFO - Started process (PID=6715) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:35:55.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:35:55.726+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:35:55.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:35:56.591+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:35:56.584+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:35:56.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:35:56.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 1.013 seconds
[2024-01-08T08:36:26.918+0000] {processor.py:161} INFO - Started process (PID=6779) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:36:26.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:36:26.924+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:36:26.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:36:27.362+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:36:27.359+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:36:27.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:36:27.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.471 seconds
[2024-01-08T08:36:57.788+0000] {processor.py:161} INFO - Started process (PID=6843) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:36:57.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:36:57.796+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:36:57.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:36:58.324+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:36:58.321+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:36:58.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:36:58.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.587 seconds
[2024-01-08T08:37:28.729+0000] {processor.py:161} INFO - Started process (PID=6907) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:37:28.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:37:28.736+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:37:28.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:37:29.233+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:37:29.231+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:37:29.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:37:29.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.555 seconds
[2024-01-08T08:37:59.906+0000] {processor.py:161} INFO - Started process (PID=6971) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:37:59.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:37:59.912+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:37:59.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:38:00.409+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:38:00.405+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:38:00.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:38:00.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.533 seconds
[2024-01-08T08:38:30.671+0000] {processor.py:161} INFO - Started process (PID=7035) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:38:30.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:38:30.685+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:38:30.685+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:38:31.214+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:38:31.211+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:38:31.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:38:31.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.582 seconds
[2024-01-08T08:39:01.692+0000] {processor.py:161} INFO - Started process (PID=7099) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:39:01.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:39:01.705+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:39:01.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:39:02.202+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:39:02.199+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:39:02.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:39:02.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.551 seconds
[2024-01-08T08:48:44.393+0000] {processor.py:161} INFO - Started process (PID=7163) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:48:44.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T08:48:44.423+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:48:44.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:48:45.820+0000] {logging_mixin.py:188} INFO - [2024-01-08T08:48:45.794+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T08:48:45.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T08:48:45.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 1.492 seconds
[2024-01-08T09:22:31.782+0000] {processor.py:161} INFO - Started process (PID=7225) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:22:31.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T09:22:31.787+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:22:31.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:22:32.255+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:22:32.253+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T09:22:32.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:22:32.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.496 seconds
[2024-01-08T09:51:40.420+0000] {processor.py:161} INFO - Started process (PID=7289) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:51:40.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T09:51:40.439+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:51:40.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:51:41.984+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:51:41.972+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T09:51:41.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:51:42.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 1.650 seconds
[2024-01-08T09:52:12.233+0000] {processor.py:161} INFO - Started process (PID=7353) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:52:12.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T09:52:12.244+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:52:12.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:52:12.723+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:52:12.720+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T09:52:12.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:52:12.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.518 seconds
[2024-01-08T09:52:43.138+0000] {processor.py:161} INFO - Started process (PID=7417) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:52:43.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T09:52:43.169+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:52:43.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:52:43.951+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:52:43.944+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T09:52:43.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:52:43.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.878 seconds
[2024-01-08T09:53:14.865+0000] {processor.py:161} INFO - Started process (PID=7483) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:53:14.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T09:53:14.876+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:53:14.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:53:15.462+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:53:15.454+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T09:53:15.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:53:15.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.652 seconds
[2024-01-08T09:53:45.631+0000] {processor.py:161} INFO - Started process (PID=7547) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:53:45.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T09:53:45.637+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:53:45.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:53:45.999+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:53:45.996+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T09:53:46.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:53:46.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.387 seconds
[2024-01-08T09:54:16.824+0000] {processor.py:161} INFO - Started process (PID=7610) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:54:16.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T09:54:16.830+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:54:16.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:54:17.207+0000] {logging_mixin.py:188} INFO - [2024-01-08T09:54:17.205+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T09:54:17.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T09:54:17.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.403 seconds
[2024-01-08T10:12:11.090+0000] {processor.py:161} INFO - Started process (PID=7672) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:12:11.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T10:12:11.101+0000] {logging_mixin.py:188} INFO - [2024-01-08T10:12:11.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:12:12.378+0000] {logging_mixin.py:188} INFO - [2024-01-08T10:12:12.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T10:12:12.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:12:12.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 1.322 seconds
[2024-01-08T10:18:04.068+0000] {processor.py:161} INFO - Started process (PID=7736) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:18:04.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T10:18:04.096+0000] {logging_mixin.py:188} INFO - [2024-01-08T10:18:04.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:18:04.976+0000] {logging_mixin.py:188} INFO - [2024-01-08T10:18:04.974+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T10:18:04.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:18:05.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.972 seconds
[2024-01-08T10:52:37.426+0000] {processor.py:161} INFO - Started process (PID=7800) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:52:37.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T10:52:37.447+0000] {logging_mixin.py:188} INFO - [2024-01-08T10:52:37.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:52:38.269+0000] {logging_mixin.py:188} INFO - [2024-01-08T10:52:38.267+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T10:52:38.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T10:52:38.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.892 seconds
[2024-01-08T11:42:37.404+0000] {processor.py:161} INFO - Started process (PID=7864) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T11:42:37.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T11:42:37.409+0000] {logging_mixin.py:188} INFO - [2024-01-08T11:42:37.409+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T11:42:38.254+0000] {logging_mixin.py:188} INFO - [2024-01-08T11:42:38.170+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T11:42:38.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T11:42:38.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 1.070 seconds
[2024-01-08T12:18:00.632+0000] {processor.py:161} INFO - Started process (PID=7928) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T12:18:00.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T12:18:00.635+0000] {logging_mixin.py:188} INFO - [2024-01-08T12:18:00.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T12:18:00.791+0000] {logging_mixin.py:188} INFO - [2024-01-08T12:18:00.788+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T12:18:00.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T12:18:00.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.179 seconds
[2024-01-08T13:08:25.593+0000] {processor.py:161} INFO - Started process (PID=7992) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T13:08:25.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T13:08:25.598+0000] {logging_mixin.py:188} INFO - [2024-01-08T13:08:25.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T13:08:25.913+0000] {logging_mixin.py:188} INFO - [2024-01-08T13:08:25.902+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T13:08:25.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T13:08:26.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.433 seconds
[2024-01-08T13:56:33.883+0000] {processor.py:161} INFO - Started process (PID=8056) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T13:56:33.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T13:56:33.891+0000] {logging_mixin.py:188} INFO - [2024-01-08T13:56:33.891+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T13:56:34.680+0000] {logging_mixin.py:188} INFO - [2024-01-08T13:56:34.634+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T13:56:34.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T13:56:34.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 1.048 seconds
[2024-01-08T14:40:43.342+0000] {processor.py:161} INFO - Started process (PID=8119) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:40:43.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:40:43.366+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:40:43.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:40:43.601+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:40:43.599+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:40:43.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:40:43.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.328 seconds
[2024-01-08T14:51:17.995+0000] {processor.py:161} INFO - Started process (PID=8184) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:51:18.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:51:18.017+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:51:18.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:51:18.795+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:51:18.782+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:51:18.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:51:18.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.911 seconds
[2024-01-08T14:51:49.714+0000] {processor.py:161} INFO - Started process (PID=8248) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:51:49.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:51:49.721+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:51:49.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:51:49.958+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:51:49.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:51:49.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:51:49.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.287 seconds
[2024-01-08T14:52:20.353+0000] {processor.py:161} INFO - Started process (PID=8312) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:52:20.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:52:20.360+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:52:20.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:52:20.574+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:52:20.571+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:52:20.575+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:52:20.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.253 seconds
[2024-01-08T14:52:50.682+0000] {processor.py:161} INFO - Started process (PID=8376) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:52:50.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:52:50.689+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:52:50.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:52:50.877+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:52:50.874+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:52:50.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:52:50.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.220 seconds
[2024-01-08T14:53:21.339+0000] {processor.py:161} INFO - Started process (PID=8440) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:53:21.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:53:21.351+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:53:21.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:53:21.604+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:53:21.600+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:53:21.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:53:21.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.312 seconds
[2024-01-08T14:53:52.116+0000] {processor.py:161} INFO - Started process (PID=8503) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:53:52.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:53:52.122+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:53:52.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:53:52.311+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:53:52.308+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:53:52.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:53:52.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.226 seconds
[2024-01-08T14:54:22.801+0000] {processor.py:161} INFO - Started process (PID=8566) to work on /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:54:22.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crawl/crawl_data.py for tasks to queue
[2024-01-08T14:54:22.812+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:54:22.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:54:22.998+0000] {logging_mixin.py:188} INFO - [2024-01-08T14:54:22.994+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crawl/crawl_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crawl/crawl_data.py", line 9, in <module>
    from scrapingant_client import ScrapingAntClient
ModuleNotFoundError: No module named 'scrapingant_client'
[2024-01-08T14:54:22.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crawl/crawl_data.py
[2024-01-08T14:54:23.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crawl/crawl_data.py took 0.277 seconds
