[2024-01-08T06:47:11.048+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ds.index_data manual__2024-01-08T06:47:01.496371+00:00 [queued]>
[2024-01-08T06:47:11.056+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ds.index_data manual__2024-01-08T06:47:01.496371+00:00 [queued]>
[2024-01-08T06:47:11.058+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-01-08T06:47:11.075+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): index_data> on 2024-01-08 06:47:01.496371+00:00
[2024-01-08T06:47:11.094+0000] {standard_task_runner.py:60} INFO - Started process 193 to run task
[2024-01-08T06:47:11.102+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ds', 'index_data', 'manual__2024-01-08T06:47:01.496371+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmplwqaveg9']
[2024-01-08T06:47:11.108+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask index_data
[2024-01-08T06:47:11.238+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ds.index_data manual__2024-01-08T06:47:01.496371+00:00 [running]> on host 71a034ea89ba
[2024-01-08T06:47:11.308+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='cuongthanhhk@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ds' AIRFLOW_CTX_TASK_ID='index_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T06:47:01.496371+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-08T06:47:01.496371+00:00'
[2024-01-08T06:47:11.315+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-08T06:47:11.318+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/index_es/index_to_es.py']
[2024-01-08T06:47:11.332+0000] {subprocess.py:86} INFO - Output:
[2024-01-08T06:47:13.128+0000] {subprocess.py:93} INFO - /opt/***/dags/index_es/index_to_es.py:69: DeprecationWarning: Passing transport options in the API method is deprecated. Use 'Elasticsearch.options()' instead.
[2024-01-08T06:47:13.140+0000] {subprocess.py:93} INFO -   helpers.bulk(es_client, result, index=index_name, request_timeout=200)
[2024-01-08T06:47:13.142+0000] {subprocess.py:93} INFO -        Unnamed: 0.15  Unnamed: 0.14  ...  REB_away  HOME_TEAM_WINS
[2024-01-08T06:47:13.144+0000] {subprocess.py:93} INFO - 0                  0              0  ...      46.0               0
[2024-01-08T06:47:13.145+0000] {subprocess.py:93} INFO - 1                  1              1  ...      40.0               1
[2024-01-08T06:47:13.147+0000] {subprocess.py:93} INFO - 2                  2              2  ...      47.0               0
[2024-01-08T06:47:13.149+0000] {subprocess.py:93} INFO - 3                  3              3  ...      39.0               1
[2024-01-08T06:47:13.150+0000] {subprocess.py:93} INFO - 4                  4              4  ...      50.0               0
[2024-01-08T06:47:13.153+0000] {subprocess.py:93} INFO - ...              ...            ...  ...       ...             ...
[2024-01-08T06:47:13.155+0000] {subprocess.py:93} INFO - 27758          27758          27758  ...      48.0               0
[2024-01-08T06:47:13.157+0000] {subprocess.py:93} INFO - 27759          27759          27759  ...      33.0               1
[2024-01-08T06:47:13.159+0000] {subprocess.py:93} INFO - 27760          27760          27760  ...      45.0               1
[2024-01-08T06:47:13.160+0000] {subprocess.py:93} INFO - 27761          27761          27761  ...      42.0               1
[2024-01-08T06:47:13.162+0000] {subprocess.py:93} INFO - 27762          27762          27762  ...      42.0               0
[2024-01-08T06:47:13.165+0000] {subprocess.py:93} INFO - 
[2024-01-08T06:47:13.166+0000] {subprocess.py:93} INFO - [27763 rows x 37 columns]
[2024-01-08T06:47:13.168+0000] {subprocess.py:93} INFO - Indexing into http://elasticsearch:9200 with index test_data_ds
[2024-01-08T06:47:13.169+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-08T06:47:13.172+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/index_es/index_to_es.py", line 90, in <module>
[2024-01-08T06:47:13.174+0000] {subprocess.py:93} INFO -     index_data(df)
[2024-01-08T06:47:13.177+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/index_es/index_to_es.py", line 69, in index_data
[2024-01-08T06:47:13.179+0000] {subprocess.py:93} INFO -     helpers.bulk(es_client, result, index=index_name, request_timeout=200)
[2024-01-08T06:47:13.180+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
[2024-01-08T06:47:13.182+0000] {subprocess.py:93} INFO -     for ok, item in streaming_bulk(
[2024-01-08T06:47:13.189+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
[2024-01-08T06:47:13.191+0000] {subprocess.py:93} INFO -     for data, (ok, info) in zip(
[2024-01-08T06:47:13.193+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
[2024-01-08T06:47:13.196+0000] {subprocess.py:93} INFO -     yield from gen
[2024-01-08T06:47:13.198+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
[2024-01-08T06:47:13.200+0000] {subprocess.py:93} INFO -     raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
[2024-01-08T06:47:13.203+0000] {subprocess.py:93} INFO - elasticsearch.helpers.BulkIndexError: 500 document(s) failed to index.
[2024-01-08T06:47:13.362+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-08T06:47:13.398+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-08T06:47:13.406+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ds, task_id=index_data, execution_date=20240108T064701, start_date=20240108T064711, end_date=20240108T064713
[2024-01-08T06:47:13.462+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-01-08T06:47:13.465+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-08T06:47:14.745+0000] {email.py:281} INFO - Sent an alert email to ['cuongthanhhk@gmail.com']
[2024-01-08T06:47:16.479+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task index_data (Bash command failed. The command returned a non-zero exit code 1.; 193)
[2024-01-08T06:47:16.546+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T06:47:16.632+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
